In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/boston.csv')
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [2]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [3]:
x = df.drop('MEDV', axis=1)
y = df['MEDV']


In [4]:
x=np.array(x)
y=np.array(y).reshape(-1,1)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [6]:
x_train

array([[1.50234e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.49480e+02, 2.49100e+01],
       [6.27390e-01, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.95620e+02, 8.47000e+00],
       [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
        3.62250e+02, 7.83000e+00],
       ...,
       [1.50100e-02, 8.00000e+01, 2.01000e+00, ..., 1.70000e+01,
        3.90940e+02, 5.99000e+00],
       [1.11604e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        1.09850e+02, 2.32700e+01],
       [2.28760e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        7.08000e+01, 1.06300e+01]])

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor


param_grid = {
    'n_neighbors': np.arange(1, 10)
}


grid_search = GridSearchCV(estimator=KNeighborsRegressor(), param_grid=param_grid, cv=5)
grid_search.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': array([1, 2, 3, 4, 5, 6, 7, 8, 9])})

In [9]:
print("Best k value: ", grid_search.best_params_['n_neighbors'])
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))

Best k value:  4
Best cross-validation score: 0.48


In [11]:
y_pred = grid_search.best_estimator_.predict(x_test)


In [13]:
display(y_pred[:5])

array([[24.975],
       [30.825],
       [15.125],
       [29.225],
       [17.275]])

In [14]:
y_pred

array([[24.975],
       [30.825],
       [15.125],
       [29.225],
       [17.275],
       [27.35 ],
       [18.725],
       [15.55 ],
       [18.35 ],
       [21.175],
       [23.725],
       [19.8  ],
       [11.9  ],
       [22.3  ],
       [24.   ],
       [21.525],
       [19.875],
       [13.925],
       [36.025],
       [11.45 ],
       [27.05 ],
       [30.425],
       [16.425],
       [20.725],
       [20.35 ],
       [15.975],
       [22.775],
       [10.95 ],
       [23.25 ],
       [22.   ],
       [22.95 ],
       [23.2  ],
       [ 9.6  ],
       [33.9  ],
       [20.35 ],
       [20.45 ],
       [22.45 ],
       [27.3  ],
       [22.525],
       [29.025],
       [21.375],
       [26.725],
       [39.8  ],
       [22.5  ],
       [26.325],
       [12.3  ],
       [16.425],
       [29.025],
       [20.325],
       [21.225],
       [22.1  ],
       [31.875],
       [17.85 ],
       [21.375],
       [29.65 ],
       [21.375],
       [11.45 ],
       [36.025],
       [22.325

In [15]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = grid_search.best_estimator_.score(x_test, y_test)

In [ ]:
print